dist/sass/_mixins/breakpoints.scss, dist/sass/_mixins/structure.scss, src/sass/_mixins/breakpoints.scss, src/sass/_mixins/structure.scss
Added:
- columns mixin
- wrapper mixin
Fixed:
- breakPoints mixin
=> Mixins and functions fixes

src/sass/_functions/units.scss, src/sass/_variables/paths.scss, src/sass/mixins.scss
Repairs to the sass-common library to allow it to be deployable
=> Sass common fixes

dist/fonts/fc-icons.scss, dist/sass/_mixins/structure.scss, dist/sass/_variables/breakpoints.scss, dist/sass/_variables/colors.scss, dist/sass/_variables/misc.scss, dist/sass/general/forms-v2.scss, dist/sass/general/useful-classes.scss, dist/sass/variables.scss, package.json, src/fonts/iconfontTemplate.scss.tpl, src/sass/_mixins/structure.scss, src/sass/_variables/breakpoints.scss, src/sass/_variables/colors.scss, src/sass/_variables/misc.scss, src/sass/general/forms-v2.scss, src/sass/general/useful-classes.scss, src/sass/variables.scss
- fixed some of the forms issues
- added a new wrap logic that works with the form layout
- rewrote the custom select style so it's easier to integrate with the form validation
=> Form fixes

src/sass/general/buttons.scss
* Added transparent button.
* Added larger button size.
=> New buttons

.scss-lint.yml
:information_desk_person: This change ignores compiled CSS files in `/dist`.
=> Ignore compiled CSS files

dist/fonts/fc-icons.scss, dist/sass/general/modal.scss, dist/sass/style.scss, dist/style.css, src/fonts/iconfontTemplate.scss.tpl, src/sass/general/modal.scss, src/sass/style.scss
Added styling for modal popups.
=> Modal popups

bower.json, package.json, sandbox.html, src/sass/general/forms-v2.scss
Changed the depracated ```<tt>``` element with a span with class ```.ui-radio/.ui-checkbox```
=> Custom radio/checkbox using a class

bower.json, package.json, src/sass/_variables/colors.scss, src/sass/general/useful-classes.scss
=> add bg + font colors

bower.json, package.json, src/fonts/iconfontTemplate.scss.tpl, src/sass/_variables/colors.scss, src/sass/general/article.scss, src/sass/general/forms-v2.scss, src/sass/general/modal.scss
- replaced the purple color with a better one
- fixed the icons for messages. we now have icons for each type of message (error, warning, info, success)
- moved the classes from icon font template to their right places.
=> Various fixes: changed colors / icons for messages / cleaner icon font template / fixed checkbox icon

bower.json, dist/sass/general/forms-v2.scss, dist/style.css, package.json, src/sass/general/forms-v2.scss
Radio and checkboxes did not have `:focus` styles.
=> Add a color to the border of selected radio- and check-buttons.

bower.json, package.json, src/sass/_mixins/fonts.scss, src/sass/general/article.scss, src/sass/general/forms-v2.scss, src/sass/general/structure.scss, src/sass/general/useful-classes.scss
Line height should be applied by default to all elements that have a font-size declared.
=> Line height

bower.json, package.json, sandbox.html, src/sass/_variables/colors.scss, src/sass/general/buttons.scss
For disabled buttons, we can now use the class ```btn--disabled``` OR the attribute ```disabled``` (```<a href="btn--primary btn--small" disabled>Click me</a>```)
=> Disabled buttons

bower.json, package.json, src/fonts/svg/uE007-info.svg, src/fonts/svg/uE012-arrow-full-right.svg, src/sass/_mixins/structure.scss, src/sass/_variables/colors.scss, src/sass/general/hero.scss, src/sass/general/useful-classes.scss
- fixed the info icon
- added new icons
- fix css issues
=> Small fixes and additions

bower.json, package.json, src/fonts/iconfontTemplate.scss.tpl, src/sass/fonts.scss
We have to revert to using Google Fonts until we can find a bulletproof solution for serving fonts across all platforms and browsers (Win + Chrome rendering issue, Win + IE font loading issue)
=> Revert to Google Fonts

bower.json, package.json, sandbox.html, src/sass/general/forms-v2.scss
Also adds a textarea placeholder to sandbox for future use.
PT: https://www.pivotaltracker.com/story/show/93029542
Devs: @emmaviolet @igoratron
=> Remove double spacing in text area

LICENCE.md, README.md, bower.json
=> Add licence information

bower.json, package.json, sandbox.html, src/fonts/svg/uE017-pencil.svg, src/sass/_variables/misc.scss, src/sass/general/forms-v2.scss
=> Pencil icon next to the inline text field.

bower.json, package.json, src/sass/_variables/misc.scss, src/sass/general/forms-v2.scss, src/sass/general/structure.scss
=> Change the margin sizes to match the old borrower style.

bower.json, package.json, src/sass/general/forms-v2.scss
https://jira.fundingcircle.com/browse/NS-15
@FundingCircle/frontend
=> Vertically align text in input fields

bower.json, package.json, src/sass/_variables/misc.scss, src/sass/general/forms-v2.scss
Fixed the styling for custom checkbox and radio inputs for IE8. Now, on IE8 they fallback to the default styling.
=> IE8 fix option elements

bower.json, package.json, sandbox.html, src/sass/general/forms-v2.scss
Related to this story https://jira.fundingcircle.com/browse/NS-16
=> Styles for autocomplete lists note elements

bower.json, package.json, sandbox.html, src/sass/general/forms-v2.scss
=> Use bottom border to highlight valid input text.

bower.json, package.json, src/sass/_functions/hero.scss, src/sass/_mixins/hero.scss, src/sass/_variables/misc.scss, src/sass/general/hero.scss
updates to the hero component according to the design specs
=> Hero mixin

bower.json, package.json, sandbox.html, src/sass/general/forms-v2.scss
=> Remove the border around fieldset elements.

bower.json, package.json, sandbox.html, src/sass/general/forms-v2.scss
=> Unify 2- and 3-column form layout under column-wrap class.

bower.json, package.json, sandbox.html, src/sass/general/forms-v2.scss
=> Add toggle switch

bower.json, package.json, src/sass/general/forms-v2.scss
Tooltip showing underneath other page content, specifically on lead gen
form
https://jira.fundingcircle.com/browse/GH-177
=> Add z-index to `form-default_tooltip`

bower.json, package.json, src/sass/_mixins/structure.scss
* Create golden ratio padding mixin
* for use in content SEO pages
=> golden ratio padding mixin

bower.json, package.json, src/sass/general/useful-classes.scss
step 1 in fixing the inconsistencies with the upper titles and making them easier to read
=> fixed font size for upper title and removed small title

bower.json, package.json, src/sass/_mixins/structure.scss, src/sass/_variables/misc.scss, src/sass/general/useful-classes.scss
* update goldenRatioPaddings mixin so padding-right is not required
* update wrap class to include option to disable
* bump patch version
=> Update goldenRatioPaddings mixin and wrap class

bower.json, gulpfile.js, package.json, src/sass/_functions/units.scss
* Build dist/ after npm install
Links
* JIRA: https://jira.fundingcircle.com/browse/RI-66
@FundingCircle/dottie :eyes:
=> [RI-66] Enable npm install for static-content

.circleci/config.yml, circle.yml, package.json
💁 Migrates the CircleCI build configuration to 2.0 format.
=> CircleCI 2.0

.circleci/config.yml, .github/CODEOWNERS, gulpfile.js, package-lock.json, package.json
Updates Ruby version to 3.3.0.
Fixes the typo in the CODEOWNERS file so that it correctly links team AFEP as owners of this repo.
Updates gulp-sass and node-sass versions so they are compatible with the newer node versions and fix breaking changes.
The existing Ruby image has been deprecated.
=> AF-999 Update Ruby version and CODEOWNERS file
